# Generated by Django 3.1.4 on 2021-01-03 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaceDetectedTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_face', models.CharField(max_length=100)),
                ('detected_date', models.DateField(auto_now_add=True)),
                ('detected_time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='personname',
            name='person_name',
            field=models.CharField(max_length=100),
        ),
    ]
