# Generated by Django 3.1.4 on 2021-01-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210103_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facedetectedtime',
            name='detected_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='facedetectedtime',
            name='detected_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
