# Generated by Django 3.1.4 on 2021-01-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210104_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facedetectedtime',
            name='detected_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='facedetectedtime',
            name='detected_time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
