# Generated by Django 3.1.4 on 2020-12-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20201231_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonsName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
