# Generated by Django 3.1.4 on 2020-12-31 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_personsname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PersonsName',
            new_name='PersonName',
        ),
    ]
