# Generated by Django 3.1.4 on 2020-12-31 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20201231_1816'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonName',
        ),
    ]
