# Generated by Django 3.1.4 on 2021-01-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_delete_personname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useralert',
            name='alert_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='useralert',
            name='alert_email_body',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='useralert',
            name='alert_email_subject',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
