# Generated by Django 3.1.4 on 2021-01-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20210105_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useralert',
            name='alert_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='useralert',
            name='alert_email_body',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='useralert',
            name='alert_email_subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
