# Generated by Django 3.1.4 on 2021-01-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20210105_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useralert',
            name='alert_email_body',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
