# Generated by Django 3.1.4 on 2021-01-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_auto_20210106_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useralert',
            name='alert_email_body',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
